### ISSUE TITLE
Adding a comment reply with enter makes it look like the comment isn't added

### ISSUE THREAD

**Issue by wilka** [int2017/Inspicio#65]
## Reproduction Steps

1. Add a comment on a review
1. Click Reply to reply to that comment
1. Type something, then press enter

## Expected

The comment to be added, and shown under the comment I'm reply to

## Actual

The comment box disapres and makes it look like it hasn't been added. But if I click Reply again (to add my comment a 2nd time) it shows up.

![adding-comments](https://user-images.githubusercontent.com/1788792/28916090-f61b050e-7838-11e7-90e3-fa750b7e229b.gif)

**Comment by gecevicius** [comment]
Fixed with #74
