### ISSUE TITLE
Going back then forwards shows the review as open then closed

### ISSUE THREAD

**Issue by wilka** [int2017/Inspicio#70]
## Reproduction Steps

1. Go to a review
1. Look at the open/closed control (it should say)
1. Press Back to go to the list of reviews
1. Press Forward to return the review page

## Expected

The review to look the same as before

## Actual

The review is now shown as closed. If you do it again, it switches back to being open. It also ticks the **urgent** checkbox.

![back-forward](https://user-images.githubusercontent.com/1788792/28933552-5ef3a4be-7875-11e7-8cbc-54ccacbefd62.gif)

**Comment by Snappiestjack** [comment]
I've been able to reproduce this issue, but have also found that when the initial state is 'closed' it does not change when navigating backwards then forwards.

![capture](https://user-images.githubusercontent.com/6187142/29017295-294c9588-7b4e-11e7-9a2e-b50ed7eb20cc.gif)

**Comment by Snappiestjack** [comment]
Looking into this a 'easyish' solution would be to **_force_** a refresh and as a result **_rehit_** the server. Basically back/forward default behaviour would change.

This would;
* A. Address this issue
* B. Address similar issues relating to commenting and the new comments not showing up when you return. 

### Question
Is this a good idea in terms of this project and in other projects. To me it seems like it would be a very project specific solution that being it's okay if the project requires this sort of implementation.

@WilkaH @kerrylewis @gecevicius

**Comment by Snappiestjack** [comment]
This may or may not be an issue once we move over to using a JS framework. Will create a branch with a fix which we can utilise if needed later on. 

Keeping this open to remind us.

**Comment by Snappiestjack** [comment]
Confirmed that this is only happening in Chrome. Works as expected in FF & Edge.

That's; 
* Chrome 59.0.3071.115 & latest 60.0.3112.90
* FF 54.0.1 
* Edge 40.15063

**Comment by Snappiestjack** [comment]
Pushed a fix for this (see above).
